theme = "hugo-theme-minos"

baseURL = "https://purchasing-officer-daisy-14376.netlify.com/"

languageCode = "zh-tw"
title = "有完沒完RRR"
enableEmoji = true
hasCJKLanguage = true

[[menu.main]]
    name = "Categories"
    url= "/Categories/index.html"
[[menu.main]]
    name = "Tags"
    url="/Tags/index.html"
    
[params]
    smartToc = true
    author = "Yi-Ju Tseng"
    disqusShortname = "rrrblog"

[taxonomies]
  category = "categories"
  tag = "tags"