theme = "hugo-theme-minos"

baseURL = "https://purchasing-officer-daisy-14376.netlify.com/"

languageCode = "zh-tw"
title = "有完沒完RRR"
enableEmoji = true


[[menu.main]]
    name = "Categories"
    url= "/Categories/"
[[menu.main]]
    name = "Tags"
    url="/Tags/"
    
[params]
    smartToc = true
    author = "Yi-Ju Tseng"

[taxonomies]
  category = "categories"
  tag = "tags"